TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = Spotify
ARCHS = arm64
THEOS_LAYOUT_DIR_NAME = layout-standalone

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MITMLyricsStudio

MITMLyricsStudio_FILES = $(shell find Sources/EeveeSpotify/ShareEditor -name '*.swift') $(shell find Sources/MITMLyricsStudio -name '*.swift') $(shell find Sources/MITMLyricsStudioC -name '*.m' -o -name '*.c' -o -name '*.mm' -o -name '*.cpp')
MITMLyricsStudio_SWIFTFLAGS = -ISources/MITMLyricsStudioC/include -Osize -DMITM_LYRICS_STANDALONE
ifeq ($(MITM_MOTION_ARTWORK_DIAGNOSTICS),1)
MITMLyricsStudio_SWIFTFLAGS += -DMITM_MOTION_ARTWORK_DIAGNOSTICS
endif
MITMLyricsStudio_FRAMEWORKS = WebKit Photos MediaPlayer ImageIO AVFoundation
MITMLyricsStudio_CFLAGS = -fobjc-arc -ISources/MITMLyricsStudioC/include -Os

include $(THEOS_MAKE_PATH)/tweak.mk

internal-stage::
	mkdir -p "$(THEOS_STAGING_DIR)/Library/Application Support/MITMLyricsStudio.bundle"
	rm -rf "$(THEOS_STAGING_DIR)/Library/Application Support/MITMLyricsStudio.bundle/ShareEditor"
	rm -rf "$(THEOS_STAGING_DIR)/Library/Application Support/MITMLyricsStudio.bundle/TimelineEditor"
	cp -R "layout/Library/Application Support/EeveeSpotify.bundle/ShareEditor" \
		"$(THEOS_STAGING_DIR)/Library/Application Support/MITMLyricsStudio.bundle/ShareEditor"
	cp -R "layout/Library/Application Support/EeveeSpotify.bundle/TimelineEditor" \
		"$(THEOS_STAGING_DIR)/Library/Application Support/MITMLyricsStudio.bundle/TimelineEditor"
